version: 2
defaults: &defaults
    machine:
      image: circleci/classic:edge
    steps:
      - run:
        name: Restart Docker with experimental features enabled
        command: |
          sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
          sudo service docker restart
      - run:
          name: Check docker is running
          command: docker info
      - run:
          name: Pull Community Hass.io Add-ons build environment
          command: docker pull hassioaddons/build-env:latest
      - run:
          name: Log in to Docker Hub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
            then
              docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
            fi
      - checkout
      - run:
          name: Get QEMU user mode processor emulation binaries
          command: |
            curl -L -s "https://github.com/hassio-addons/qemu-user-static/releases/download/v2.10.1/qemu-aarch64-static.tar.gz" | tar zxvf - -C ./debian-base/rootfs/usr/bin/
            curl -L -s "https://github.com/hassio-addons/qemu-user-static/releases/download/v2.10.1/qemu-arm-static.tar.gz" | tar zxvf - -C ./debian-base/rootfs/usr/bin/
      - deploy:
          name: Build and (maybe) deploy
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                docker run \
                  --privileged \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v ~/.docker:/root/.docker \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --target debian-base \
                  --${ARCH} \
                  --git \
                  --push
              else
                docker run \
                  --privileged \
                  -v /var/run/docker.sock:/var/run/docker.sock \
                  -v "$PWD":/docker \
                  hassioaddons/build-env:latest \
                  --target debian-base \
                  --git \
                  --${ARCH}
              fi
      - deploy:
          name: Send notification to Microbadger
          command: |
              if [[ "${CIRCLE_BRANCH}" = "master" || ! -z "${CIRCLE_TAG:-}" ]];
              then
                curl -X POST https://hooks.microbadger.com/images/${MICROBADGER_WEBHOOK}
              fi

jobs:
  aarch64:
    <<: *defaults
    environment:
      ARCH: aarch64
      MICROBADGER_WEBHOOK: hassioaddons/debian-base-aarch64/xPXzVNfmlHE-TbnO6_v2_G5XVt4=
  amd64:
    <<: *defaults
    environment:
      ARCH: amd64
      MICROBADGER_WEBHOOK: hassioaddons/debian-base-amd64/9VpSGXcF3-G8pL-mKXq-0WWvG3g=
  armhf:
    <<: *defaults
    environment:
      ARCH: armhf
      MICROBADGER_WEBHOOK: hassioaddons/debian-base-armhf/PzdnuORNZ7a76EmFKI1mrby2p74=
  i386:
    <<: *defaults
    environment:
      ARCH: i386
      MICROBADGER_WEBHOOK: hassioaddons/debian-base-i386/te8Hu20AiumjGJbSK0Bf99iivhI=

workflows:
  version: 2
  build_and_maybe_deploy:
    jobs:
      - aarch64:
          filters:
            tags:
              only: /.*/
      - amd64:
          filters:
            tags:
              only: /.*/
      - armhf:
          filters:
            tags:
              only: /.*/
      - i386:
          filters:
            tags:
              only: /.*/
