---
name: Debian Base Image with added scanning support
version: dev
slug: debian-base-sannsupport
description: Docker Debian base images used by Home Assistant Community Add-ons with added scanning support
url: https://github.com/connum/addon-debian-base-scansupport
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
